version: "3.3"

services:

  postgres:
    image: postgres:9.6
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgraphile
      POSTGRES_PASSWORD: postgraphile
      POSTGRES_DATABASE: postgraphile

  api:
    build: .
    ports:
      - "5000:5000"
    links:
      - postgres
    command: [
        "--cors",
        "--watch",
        "--disable-default-mutations",
        "--body-size-limit",
        "5MB",
        "--connection",
        "postgresql://postgraphile:postgraphile@postgres/postgraphile",
        "--enhance-graphiql",
    ]

volumes:
  postgres-data: {}
